---
title: "The Root of Me"
date: "2025-10-14"
title-block-banner: false
format:
  html:
    toc: false
    css: 
      - /assets/css/styles.css   
      - /assets/css/essays.css 
---
_“Well, I have a trade of my own. I suppose I am the only one in the world. I’m a consulting detective, if you can understand what that is.”_

For a long time, I have drifted through streams of time, looking for a shore to drop my anchor in. During my engineering days at **GNDEC, Ludhiana**, I thought that my soul belonged to the digital world of 0s and 1s. But over the course of time, it dawned on me that I had romanticized the digital world of 0s and 1s for cold, economic reasons. For me, they were nothing more than tools of creation. My search for the shore continued.

This search slowly turned into a pursuit of knowledge about the inner workings of our modern world and led me to **IIM Trichy**. At IIM Trichy, I rediscovered my passion for numbers, this time in the form of analytics. This rediscovery led me to a crossroad where I had to decide between Operations and Finance as my specialization in the second year of my MBA. The sheer monotony of Operations and the siren call of Finance made the choice easy for me. But the journey afterwards has certainly not been an easy one.

My journey with Finance began on an adversarial note. The bureaucratic language that envelops every pore of Finance and the imprudence of accounting laws came very close to making me give up on it. But then, by the invisible hands of fate and my own ego, I found myself in a Valuations class. And like a classic enemies-to-lovers trope, I fell in love with Finance. To be more precise, I fell in love with the way numbers can be used to tell and understand the stories of businesses, nations, the world, and our own selves. That was when I knew that I had found my shore.

For helping me find my shore, I will always be grateful to my professors at IIM Trichy, particularly **Vinu C.T., Saumen Majumdar, Narahari Hansoge, and Alka Chadha**.

This website is my attempt at anchoring myself to my shore — the shore where I can be independent of the dictates of algorithms, the vagaries of online platforms, and the hustle culture of NPCs. It is my attempt to be free and to share quantitative stories that intrigue, influence, and inspire me. 

Hoping that, unlike my previous attempts, I will not get lost to the time and mind storms of my own making.